### ISSUE TITLE
Python 3.10: Can't create a device key: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by tom4tom** [moddevices/mod-ui#126]
Hi,
anyone know what do do?

**Comment by falkTX** [comment]
I dont even know what this is.
using virtualenv I am able to make things work with python3.10, alike https://github.com/moddevices/mod-panel/blob/master/source/mod-ui.sh#L32

**Comment by tom4tom** [comment]
Hi falkTX,

more information:
Can't create a device key: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Traceback (most recent call last):
  File "/home/ubuntu/mod-ui/server.py", line 54, in <module>
    from mod import webserver
  File "/home/ubuntu/mod-ui/mod/webserver.py", line 30, in <module>
    from tornado import gen, iostream, web, websocket
  File "/home/ubuntu/mod-ui/modui-env/lib/python3.10/site-packages/tornado/web.py", line 85, in <module>
    from tornado import httputil
  File "/home/ubuntu/mod-ui/modui-env/lib/python3.10/site-packages/tornado/httputil.py", line 101, in <module>
    class HTTPHeaders(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

**Comment by falkTX** [comment]
A small modification is needed for the last error, see the script I posted on the last message

**Comment by tom4tom** [comment]
Thanks falkTX, now it works ;-)

**Comment by falkTX** [comment]
Added a note for the py3.10 workaround in efd6bdc65d78033ff639ddd648b3530a68305b3f
